# Generated by Django 5.0.3 on 2024-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
